import type { Metadata } from "next";
import dynamic from "next/dynamic";
import "./globals.css";
import Header from "@/components/header/Header";
const Footer = dynamic(() => import("@/components/Footer/Footer"));
const FastCall = dynamic(() => import("@/components/ui/fastCall"));
const ScrollToTop = dynamic(() => import("@/components/ui/ScrollToTop"));
const CompanyGoogleMap = dynamic(
  () => import("@/components/companyGoogleMap/companyGoogleMap")
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="antialiased w-full">
        <Header />
        <main className="pt-[72px] lg:pt-[132px] xl:pt-[142px]">
          {children}
        </main>
        <CompanyGoogleMap />
        <Footer />
        {/*   fast icons for demo or call fixed on right */}
        <FastCall />
        {/* Scroll to top button fixed on left bottom */}
        <ScrollToTop />
      </body>
    </html>
  );
}
